### ISSUE TITLE
Azure Storage Backend does not work with editor

### ISSUE THREAD

**Issue by aucubin** [kestra-io/storage-azure#54]
### Expected Behavior

When using azure blob storage as storage backend for Kestra the editor should work correctly and show the file tree of a given namespace and allow files or directories to be added.

### Actual Behaviour

Using azure blob storage as storage backend causes the editor file tree to not work.

![image](https://github.com/kestra-io/storage-azure/assets/17550349/1e306531-cfda-474c-ae70-2dd4934fe733)

Files like README will get opened correctly, but the file tree is not working and clicking on it will cause a file not found error:
![image](https://github.com/kestra-io/storage-azure/assets/17550349/1d0d2401-80d5-40dc-a3f9-a41618c4d0db)

Clicking create new file will show the error **Unable to resolve nonexistent file kestra://myteam**.

Trying to create new files/directories in the editor also does not work.

On the request side I can see that GET /api/v1/namespaces/myteam/files/stats?path= returns 404, with the message "Not Found: _files (File not found)". POST /api/v1/namespaces/myteam/files/stats?path= returns 400 with the message "Bad Request: Required QueryValue [path] not specified".

On the azure portal I can see that the folders are created, although there is a folder without a name created by kestra in the storage container, where the files are copied in.

![image](https://github.com/kestra-io/storage-azure/assets/17550349/5d2c30dc-8c4d-42e3-b63e-e6d6f85f1482)
![image](https://github.com/kestra-io/storage-azure/assets/17550349/37abd7ee-03c5-41cd-9911-cf680d7f0ab6)

### Steps To Reproduce

1. Set up Kestra with Azure as Storage Backend as per documentation.
2. Create a flow.
3. Click on the editor in the sidebar.
4. No file tree list is shown and no files can be added in the editor

### Environment Information

- Kestra Version: 0.16.6
- Plugin version: Latest version
- Operating System (OS / Docker / Kubernetes): Happens both in the docker compose and in a freshly set up AKS cluster with the latest helm chart version of kestra (0.16.0 from https://helm.kestra.io).
- Java Version (If not docker):

**Comment by loicmathieu** [comment]
We will change the namespace file editor in 0.17.0 but we should make sure it works also with the Azure blob storage so I keep this issue opened so we don't forgot to test this storage.

**Comment by brian-mulier-p** [comment]
@Ben8t / @anna-geller if you QA the new editor :+1:

**Comment by Ben8t** [comment]
1. See screenshot attached; when creating a folder I hit a 404 response error
2. When I create a file (without any folder), the file seemed to be created but when refreshing my browser it disapears :thinking_face: (only cache I guess)

![Screenshot 2024-05-27 at 10 02 41](https://github.com/kestra-io/storage-azure/assets/46634684/c86fbe7a-77ad-458f-aa87-66422e888c19)

**Comment by brian-mulier-p** [comment]
Fixed :) There was a bunch of exists method that were based on the fact that Azure SDK would return entries for directories but it's not the case when the above option is disabled. I switched to checking our special directory marker file entry instead

**Comment by brian-mulier-p** [comment]
@Ben8t if you have some time to test it again (everything, not only the editor) feel free to as I touched a bit of everything :+1: This is building [here](https://github.com/kestra-io/kestra/actions/runs/9272527920)

**Comment by brian-mulier-p** [comment]
Well it looks like there is some remaining work as I still get some 404

**Comment by brian-mulier-p** [comment]
Should be good now, I tested it on a Kestra instance and everything seems to work so far. Still if you want to give it another QA @Ben8t you can. Note that my changes could have impacted more than only namespace files

**Comment by Ben8t** [comment]
FYI, everything works with both container setup (hierchical enabled or not), still have the <no name> folder though for reference

![image](https://github.com/kestra-io/storage-azure/assets/46634684/cad9b612-ae50-476f-b396-f63f0df43caa)

**Comment by brian-mulier-p** [comment]
Yes it's normal in the non-hierarchical storage but won't have any impact, still thank's for noticing :+1:
